# Generated by Django 4.2.6 on 2023-11-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_visit_visit_date_time_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vist', to='api.schedule'),
        ),
    ]
