# Generated by Django 4.2.6 on 2023-11-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_schedule_visit_visit_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
    ]
