# Generated by Django 4.2.6 on 2023-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_schedule_patient_remove_visit_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
