# Generated by Django 4.2.6 on 2023-11-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_visit_rating_set_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
